manualdefault:
  image: node:latest

stages:
  - build_job 

cache:
  paths:
    - node_modules/

build_job:
  stage: build_job
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_envet" &&  $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: manual

  script:
    - echo "Install Packages NPM ..."
    - npm install
    - echo "Install Angular-CLI ..."
    - npm install -g @angular/cli
    - echo "Buldin Project Angular"
    - ng build
